@BASE_URL = http://localhost:3000

GET {{BASE_URL}}

###
GET {{BASE_URL}}/1

###
POST {{BASE_URL}}/admin/post/add
Content-Type: application/json

{
    "title": "Title1",
    "description": "Desc For Title 1",
    "imageUrl": "test.png"
}